/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignRouteImport } from './routes/sign'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as IndexRouteImport } from './routes/index'

const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/sign': typeof SignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/sign': typeof SignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/sign': typeof SignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preview' | '/scan' | '/send' | '/settings' | '/sign'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview' | '/scan' | '/send' | '/settings' | '/sign'
  id: '__root__' | '/' | '/preview' | '/scan' | '/send' | '/settings' | '/sign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewRoute: typeof PreviewRoute
  ScanRoute: typeof ScanRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewRoute: PreviewRoute,
  ScanRoute: ScanRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
